pipelines:

  - name: test_jenkins_git
    steps:
#     - name: print_results2
#       type: Bash
# #       configuration:
# #         inputSteps:
# #           - name: test_app2
# #         inputResources:
# #           - name: jenkins_reource_git
#       execution:
#         onExecute:
#           - printenv

    - name: test_app
      type: Jenkins
      configuration:
        priority: 1   
#         timeoutSeconds: 1        
        jenkinsJobName: github/multibranch
        jenkinsBranchName: {{gitBranch}}
        buildParameters:
            PARAM1: value1
            PARAM2: value2
            PARAM3: value3
        integrations:
          - name: jenkins
#         inputSteps:
#           - name: print_results2          
        outputResources:
          - name: jenkins_job_master
    - name: print_results
      type: Bash
      configuration:
        priority: 10000 
#         inputSteps:
#           - name: test_app        
        inputResources:
          - name: jenkins_job_master
      execution:
        onExecute:
          - printenv

#     - name: jfrog_jenkins_freestyle
#       type: Jenkins
#       configuration:
#         jenkinsJobName: var_freestyle_proj
#         integrations:
#           - name: jenkins
#         inputSteps:
#           - name: print_results2
# #         inputResources:
# #           - name: my_jenkins_pb

#     - name: test_app2
#       type: Jenkins
#       configuration:
#         priority: 1      
#         jenkinsJobName: github/multibranch
#         jenkinsBranchName: {{gitBranch}}
#         buildParameters:
#             PARAM1: value1
#             PARAM2: value2
#             PARAM3: value3
#         integrations:
#           - name: jenkins
#         outputResources:
#           - name: jenkins_reource_git

#     - name: print_results2
#       type: Bash
#       configuration:
#         inputSteps:
#           - name: test_app2
#         inputResources:
#           - name: jenkins_reource_git
#       execution:
#         onExecute:
#           - printenv
